### ISSUE TITLE
Failed to download nonces file

### ISSUE THREAD

**Issue by alivebao** [handshake-org/hs-tree-data#3]
I followed with the claim guide(https://www.namebase.io/airdrop), but when I execute the /bin/hs-airdrop(step 4), it always show like below:
```
Downloading: https://github.com/handshake-org/hs-tree-data/raw/master/nonces/188
.bin...
Error: connect ETIMEDOUT 52.74.223.119:443
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)

```

**Comment by pinheadmz** [comment]
please see https://github.com/handshake-org/hs-airdrop/issues/37

**Comment by jin10086** [comment]
@alivebao  you can use proxy  or  manual download https://github.com/handshake-org/hs-tree-data/raw/master/nonces/188.bin  then move to ~/.hs-tree-data/nonces

**Comment by alivebao** [comment]
Worked, thanks a lot! @jin10086 @pinheadmz

**Comment by overtrue** [comment]
```bash
git clone https://github.com/handshake-org/hs-tree-data ~/.hs-tree-data
```
