### ISSUE TITLE
My key was not found in the airdrop tree

### ISSUE THREAD

**Issue by luismulinari** [handshake-org/hs-tree-data#5]
I've been trying to claim my Handshake Airdrop but I'm getting the following error:

```
NonceError: Could not find nonce in bucket 252.
...
This means your key was not found in the airdrop tree.
If you registered at handshake.org, use that address.
```

My GitHub account was created many years ago and I have enough followers. The only clue that I have is the fact that I did not have any `SSH or GPG keys` on my GitHub account during the week of 2019-02-04, since I use personal access tokens to access my account.

**Comment by pinheadmz** [comment]
>  I did not have any SSH or GPG keys on my GitHub account during the week of 2019-02-04

This was a requirement to receive an airdrop

**Comment by luismulinari** [comment]
> If you had 15 or more followers on github during the week of 2019-02-04, your github SSH & PGP keys are included in the merkle tree.

The requirement is: `If you had 15 or more followers on github during the week of 2019-02-04`, no?

**Comment by pinheadmz** [comment]
From https://github.com/handshake-org/hs-airdrop

> The top ~250,000 users on github have had their SSH keys and PGP added to a merkle tree. Out of those ~250,000 users, ~175,000 of them had valid SSH and PGP keys at the time of tree creation.
> 
> If you had 15 or more followers on github during the week of 2019-02-04, your github SSH & PGP keys are included in the merkle tree.

If you don't have a key, there is no way to send you an airdrop. The only alternative was to sign up at handshake.org during 2018 and register for the faucet, which used mainnet Handshake addresses only. I'm sorry.

**Comment by luismulinari** [comment]
@pinheadmz 

> If you had 15 or more followers on github during the week of 2019-02-04, your github SSH & PGP keys are included in the merkle tree.

https://github.com/handshake-org/hs-airdrop/commit/cd90f42cf806dc4c037b03db5548cd14e3a5852a#diff-04c6e90faac2675aa89e2176d2eec7d8R12

The requirement is: `If you had 15 or more followers on github during the week of 2019-02-04`. 

If the `SSH or PGP` was also a requirement, the requirement should be:
`15 or more followers on github during the week of 2019-02-04 *AND* a github SSH or PGP`

**Comment by pinheadmz** [comment]
I'm sorry if the documentation was misleading, please open a pull request to update the README on hs-airdrop if you think that will help users in the future.

**Comment by luismulinari** [comment]
No problem. I was just trying to understand.
